# Generated by Django 2.0 on 2018-04-19 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gce_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet_annonce', models.CharField(blank=True, db_column='sujet_Annonce', max_length=500, null=True)),
                ('description_annonce', models.CharField(blank=True, db_column='description_Annonce', max_length=10000, null=True)),
                ('date_annonce', models.DateField(blank=True, db_column='date_Annonce', null=True)),
                ('heure_annonce', models.TimeField(blank=True, db_column='heure_Annonce', null=True)),
                ('afficher_annonce', models.BooleanField(db_column='afficher_Annonce', default=False)),
            ],
            options={
                'db_table': 'Annonce',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_consultation', models.CharField(blank=True, db_column='sale_Consultation', max_length=250, null=True)),
                ('date_consultation', models.DateField(blank=True, db_column='date_Consultation', null=True)),
                ('heure_consultation', models.TimeField(blank=True, db_column='heure_Consultation', null=True)),
                ('afficher_consultation', models.BooleanField(db_column='afficher_Consultation', default=False)),
                ('approve_consultation', models.BooleanField(db_column='approve_Consultation', default=False)),
            ],
            options={
                'db_table': 'Consultation',
            },
        ),
        migrations.CreateModel(
            name='Copie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_copie', models.CharField(db_column='annee_Copie', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Copie',
            },
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Correction',
            },
        ),
        migrations.CreateModel(
            name='DiscussionAdministrative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Discussion_Administrative',
            },
        ),
        migrations.CreateModel(
            name='DiscussionReclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Discussion_Reclamation',
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Domaine',
            },
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Faculte',
            },
        ),
        migrations.CreateModel(
            name='FichierCopie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement_fichier', models.FileField(blank=True, db_column='emplacement_Fichier', null=True, upload_to=gce_app.models.copies_file_path)),
            ],
            options={
                'db_table': 'FichierCopie',
            },
        ),
        migrations.CreateModel(
            name='FichierCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement_fichier', models.FileField(blank=True, db_column='emplacement_Fichier', null=True, upload_to=gce_app.models.corrections_file_path)),
                ('id_correction', models.ForeignKey(blank=True, db_column='id_Correction', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Correction')),
            ],
            options={
                'db_table': 'FichierCorrection',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000)),
                ('id_domaine', models.ForeignKey(db_column='id_Domaine', on_delete=django.db.models.deletion.CASCADE, to='gce_app.Domaine')),
            ],
            options={
                'db_table': 'Filiere',
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'Groupe',
            },
        ),
        migrations.CreateModel(
            name='MessagesAdministrative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_message', models.CharField(blank=True, db_column='contenu_Message', max_length=10000, null=True)),
                ('date_message', models.DateField(blank=True, db_column='date_Message', null=True)),
                ('heure_message', models.TimeField(blank=True, db_column='heure_Message', null=True)),
                ('id_emetteur', models.CharField(blank=True, db_column='id_Emetteur', max_length=100, null=True)),
                ('id_recepteur', models.CharField(blank=True, db_column='id_Recepteur', max_length=100, null=True)),
                ('id_discussion', models.ForeignKey(blank=True, db_column='id_Discussion', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.DiscussionAdministrative')),
            ],
            options={
                'db_table': 'Messages_Administrative',
            },
        ),
        migrations.CreateModel(
            name='MessagesReclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_message', models.CharField(blank=True, db_column='contenu_Message', max_length=10000, null=True)),
                ('date_message', models.DateField(blank=True, db_column='date_Message', null=True)),
                ('heure_message', models.TimeField(blank=True, db_column='heure_Message', null=True)),
                ('id_emetteur', models.CharField(blank=True, db_column='id_Emetteur', max_length=100, null=True)),
                ('id_recepteur', models.CharField(blank=True, db_column='id_Recepteur', max_length=100, null=True)),
                ('id_discussion', models.ForeignKey(blank=True, db_column='id_Discussion', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.DiscussionReclamation')),
            ],
            options={
                'db_table': 'Messages_Reclamation',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_module', models.CharField(blank=True, db_column='titre_Module', max_length=1000, null=True)),
                ('finsaisie_module', models.BooleanField(db_column='FinSaisie_Module', default=False)),
            ],
            options={
                'db_table': 'Module',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet_notification', models.CharField(blank=True, db_column='sujet_Notification', max_length=100, null=True)),
                ('description_notification', models.CharField(blank=True, db_column='description_Notification', max_length=250, null=True)),
                ('vue_notification', models.BooleanField(db_column='vue_Notification', default=False)),
                ('date_notification', models.DateField(blank=True, db_column='date_Notification', null=True)),
                ('heure_notification', models.TimeField(blank=True, db_column='heure_Notification', null=True)),
                ('icon_notification', models.CharField(blank=True, db_column='IconPath', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('id_filiere', models.ForeignKey(db_column='id_Filiere', on_delete=django.db.models.deletion.CASCADE, to='gce_app.Filiere')),
            ],
            options={
                'db_table': 'Parcours',
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet_reclamation', models.CharField(blank=True, db_column='Sujet_Reclamation', max_length=500, null=True)),
                ('regler_reclamation', models.BooleanField(db_column='regler_Reclamation', default=False)),
                ('description_reclamation', models.CharField(blank=True, db_column='Description_Reclamation', max_length=10000, null=True)),
                ('id_module', models.ForeignKey(blank=True, db_column='id_Module', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Module')),
            ],
            options={
                'db_table': 'Reclamation',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'Section',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000)),
                ('id_parcours', models.ForeignKey(db_column='id_Parcours', on_delete=django.db.models.deletion.CASCADE, to='gce_app.Parcours')),
            ],
            options={
                'db_table': 'Specialite',
            },
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Universite',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('type_utilisateur', models.CharField(choices=[('etud', 'Etudiant'), ('ensg', 'Enseignant'), ('tech', 'Technicien'), ('chef', 'Chef Departement')], db_column='type_Utilisateur', max_length=255, null=True)),
                ('id_utilisateur', models.CharField(blank=True, db_column='id_Utilisateur', editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('avatar_utilisateur', models.FileField(db_column='Avatar', default='avatars/default_avatar.png', upload_to=gce_app.models.avatars_file_path)),
            ],
            options={
                'db_table': 'Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='VersionCopie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.IntegerField(blank=True, db_column='numero_Version', null=True)),
                ('note_version', models.FloatField(blank=True, db_column='note_Version', null=True)),
                ('id_copie', models.ForeignKey(blank=True, db_column='id_Copie', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Copie')),
            ],
            options={
                'db_table': 'VersionCopie',
            },
        ),
        migrations.CreateModel(
            name='ChefDepartement',
            fields=[
                ('id_chef_departement', models.OneToOneField(db_column='id_Utilisateur', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gce_app.Utilisateur')),
            ],
            options={
                'db_table': 'Chef_Departement',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id_enseignant', models.OneToOneField(db_column='id_Utilisateur', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gce_app.Utilisateur')),
            ],
            options={
                'db_table': 'Enseignant',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id_etudiant', models.OneToOneField(db_column='id_Utilisateur', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gce_app.Utilisateur')),
            ],
            options={
                'db_table': 'Etudiant',
            },
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id_technicien', models.OneToOneField(db_column='id_Utilisateur', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gce_app.Utilisateur')),
            ],
            options={
                'db_table': 'Technicien',
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='info_utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='id_specialite',
            field=models.ForeignKey(db_column='id_Specialite', on_delete=django.db.models.deletion.CASCADE, to='gce_app.Specialite'),
        ),
        migrations.AddField(
            model_name='notification',
            name='id_utilisateur',
            field=models.ForeignKey(blank=True, db_column='id_Utilisateur', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Utilisateur'),
        ),
        migrations.AddField(
            model_name='module',
            name='id_specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Specialite'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='id_section',
            field=models.ForeignKey(db_column='id_Section', on_delete=django.db.models.deletion.CASCADE, to='gce_app.Section'),
        ),
        migrations.AddField(
            model_name='fichiercopie',
            name='id_version',
            field=models.ForeignKey(blank=True, db_column='id_Version', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.VersionCopie'),
        ),
        migrations.AddField(
            model_name='faculte',
            name='id_universite',
            field=models.ForeignKey(blank=True, db_column='id_Universite', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Universite'),
        ),
        migrations.AddField(
            model_name='domaine',
            name='id_faculte',
            field=models.ForeignKey(blank=True, db_column='id_Faculte', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Faculte'),
        ),
        migrations.AddField(
            model_name='discussionreclamation',
            name='id_reclamation',
            field=models.ForeignKey(blank=True, db_column='id_Reclamation', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Reclamation'),
        ),
        migrations.AddField(
            model_name='correction',
            name='id_module',
            field=models.ForeignKey(blank=True, db_column='id_Module', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Module'),
        ),
        migrations.AddField(
            model_name='copie',
            name='id_module',
            field=models.ForeignKey(blank=True, db_column='id_Module', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Module'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='id_module',
            field=models.ForeignKey(blank=True, db_column='id_Module', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Module'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='id_module',
            field=models.ForeignKey(blank=True, db_column='id_Module', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Module'),
        ),
        migrations.AddField(
            model_name='technicien',
            name='id_faculte',
            field=models.ForeignKey(db_column='id_Faculte', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Faculte'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='id_etudiant',
            field=models.ForeignKey(blank=True, db_column='id_Utilisateur', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Etudiant'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='id_chef_departement',
            field=models.ForeignKey(blank=True, db_column='id_Utilisateur', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.ChefDepartement'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='id_groupe',
            field=models.ForeignKey(db_column='id_Groupe', on_delete=django.db.models.deletion.CASCADE, to='gce_app.Groupe'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='filieres',
            field=models.ManyToManyField(blank=True, to='gce_app.Filiere'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='modules',
            field=models.ManyToManyField(blank=True, to='gce_app.Module'),
        ),
        migrations.AddField(
            model_name='discussionreclamation',
            name='id_enseignant',
            field=models.ForeignKey(blank=True, db_column='id_Utilisateur', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Enseignant'),
        ),
        migrations.AddField(
            model_name='discussionadministrative',
            name='id_chef_departement',
            field=models.ForeignKey(blank=True, db_column='id_Utilisateur', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.ChefDepartement'),
        ),
        migrations.AddField(
            model_name='discussionadministrative',
            name='id_enseignant',
            field=models.ForeignKey(blank=True, db_column='id_Utilisateur_1', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Enseignant'),
        ),
        migrations.AddField(
            model_name='correction',
            name='id_enseignant',
            field=models.ForeignKey(blank=True, db_column='id_Utilisateur', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Enseignant'),
        ),
        migrations.AddField(
            model_name='copie',
            name='id_etudiant',
            field=models.ForeignKey(blank=True, db_column='id_Utilisateur', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Etudiant'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='id_enseignant',
            field=models.ForeignKey(blank=True, db_column='id_Utilisateur', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Enseignant'),
        ),
    ]
