# Generated by Django 2.0 on 2018-03-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copie',
            name='annee_copie',
            field=models.CharField(db_column='annee_Copie', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='date_Notification',
            field=models.DateField(blank=True, db_column='date_Notification', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='heure_Notification',
            field=models.TimeField(blank=True, db_column='heure_Notification', null=True),
        ),
    ]
