# Generated by Django 2.0 on 2018-04-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='titre_module',
            field=models.CharField(blank=True, db_column='titre_Module', max_length=1000, null=True, unique=True),
        ),
    ]
