# Generated by Django 2.0 on 2018-03-10 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appartientfaculte',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='appartientfaculte',
            name='id_faculte',
        ),
        migrations.RemoveField(
            model_name='appartientfaculte',
            name='id_technicien',
        ),
        migrations.AlterUniqueTogether(
            name='enseigne',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='enseigne',
            name='id_enseignant',
        ),
        migrations.RemoveField(
            model_name='enseigne',
            name='id_module',
        ),
        migrations.AlterUniqueTogether(
            name='etudier',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='etudier',
            name='id_etudiant',
        ),
        migrations.RemoveField(
            model_name='etudier',
            name='id_module',
        ),
        migrations.AlterUniqueTogether(
            name='gerermod',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='gerermod',
            name='id_chef_departement',
        ),
        migrations.RemoveField(
            model_name='gerermod',
            name='id_module',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='id_filiere',
        ),
        migrations.AddField(
            model_name='chefdepartement',
            name='modules',
            field=models.ManyToManyField(to='gce_app.Module'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='filieres',
            field=models.ManyToManyField(blank=True, to='gce_app.Filiere'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='modules',
            field=models.ManyToManyField(blank=True, to='gce_app.Module'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='modules',
            field=models.ManyToManyField(blank=True, to='gce_app.Module'),
        ),
        migrations.AddField(
            model_name='module',
            name='id_specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Specialite'),
        ),
        migrations.AddField(
            model_name='technicien',
            name='id_faculte',
            field=models.ForeignKey(db_column='id_Faculte', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Faculte'),
        ),
        migrations.DeleteModel(
            name='Appartientfaculte',
        ),
        migrations.DeleteModel(
            name='Enseigne',
        ),
        migrations.DeleteModel(
            name='Etudier',
        ),
        migrations.DeleteModel(
            name='Gerermod',
        ),
    ]
