# Generated by Django 2.0 on 2018-03-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0002_auto_20180327_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date_Notification',
            new_name='date_notification',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='heure_Notification',
            new_name='heure_notification',
        ),
    ]
