# Generated by Django 2.0 on 2018-04-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0002_auto_20180419_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='copie',
            name='afficher_copie',
            field=models.BooleanField(db_column='afficher_Copie', default=False),
        ),
        migrations.AddField(
            model_name='copie',
            name='modifiable',
            field=models.BooleanField(db_column='Modifiable', default=True),
        ),
    ]
