# Generated by Django 2.0 on 2018-03-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0003_auto_20180327_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='icon_notification',
            field=models.CharField(blank=True, db_column='IconPath', max_length=1000, null=True),
        ),
    ]
