# Generated by Django 2.0 on 2018-04-20 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0003_auto_20180419_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichiercopie',
            name='id_module',
            field=models.ForeignKey(blank=True, db_column='id_Module', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Module'),
        ),
    ]
