# Generated by Django 2.0 on 2018-03-12 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0003_auto_20180311_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionCopie',
            fields=[
                ('id_version', models.CharField(db_column='id_Version', max_length=100, primary_key=True, serialize=False)),
                ('numero_version', models.IntegerField(blank=True, db_column='numero_Version', null=True)),
                ('note_copie', models.FloatField(blank=True, db_column='note_Copie', null=True)),
                ('emplacement_copie', models.CharField(blank=True, db_column='emplacement_Copie', max_length=10000, null=True)),
            ],
            options={
                'db_table': 'VersionCopie',
            },
        ),
        migrations.RemoveField(
            model_name='copie',
            name='emplacement_copie',
        ),
        migrations.RemoveField(
            model_name='copie',
            name='note_copie',
        ),
        migrations.AddField(
            model_name='versioncopie',
            name='id_copie',
            field=models.ForeignKey(blank=True, db_column='id_Copie', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Copie'),
        ),
    ]
