# Generated by Django 2.0 on 2018-03-13 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0004_auto_20180312_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierCopie',
            fields=[
                ('id_fichier', models.CharField(db_column='id_Fichier', max_length=100, primary_key=True, serialize=False)),
                ('emplacement_fichier', models.FileField(blank=True, db_column='emplacement_Fichier', null=True, upload_to='')),
            ],
            options={
                'db_table': 'FichierCopie',
            },
        ),
        migrations.CreateModel(
            name='FichierCorrection',
            fields=[
                ('id_fichier', models.CharField(db_column='id_Fichier', max_length=100, primary_key=True, serialize=False)),
                ('emplacement_fichier', models.FileField(blank=True, db_column='emplacement_Fichier', null=True, upload_to='')),
            ],
            options={
                'db_table': 'FichierCorrection',
            },
        ),
        migrations.RemoveField(
            model_name='correction',
            name='emplacement_correction',
        ),
        migrations.RemoveField(
            model_name='versioncopie',
            name='emplacement_copie',
        ),
        migrations.AddField(
            model_name='fichiercorrection',
            name='id_correction',
            field=models.ForeignKey(blank=True, db_column='id_Correction', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Correction'),
        ),
        migrations.AddField(
            model_name='fichiercopie',
            name='id_version',
            field=models.ForeignKey(blank=True, db_column='id_Version', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.VersionCopie'),
        ),
    ]
