# Generated by Django 2.0 on 2018-04-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0004_notification_icon_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='regler_reclamation',
            field=models.BooleanField(db_column='regler_Reclamation', default=False),
        ),
    ]
