# Generated by Django 2.0 on 2018-04-21 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0004_fichiercopie_id_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichiercopie',
            name='id_version',
            field=models.ForeignKey(blank=True, db_column='id_Version', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gce_app.VersionCopie'),
        ),
    ]
