# Generated by Django 2.0 on 2018-04-24 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0005_auto_20180421_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(db_column='annee_Scolaire', max_length=500, null=True)),
            ],
            options={
                'db_table': 'anneeScolaire',
            },
        ),
        migrations.AlterField(
            model_name='copie',
            name='annee_copie',
            field=models.ForeignKey(blank=True, db_column='annee_Copie', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gce_app.AnneeScolaire'),
        ),
    ]
