# Generated by Django 2.0 on 2018-03-13 23:52

from django.db import migrations, models
import gce_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0006_auto_20180313_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichiercopie',
            name='emplacement_fichier',
            field=models.FileField(blank=True, db_column='emplacement_Fichier', null=True, upload_to=gce_app.models.copies_file_path),
        ),
        migrations.AlterField(
            model_name='fichiercorrection',
            name='emplacement_fichier',
            field=models.FileField(blank=True, db_column='emplacement_Fichier', null=True, upload_to=gce_app.models.corrections_file_path),
        ),
    ]
