# Generated by Django 2.0 on 2018-04-04 19:33

from django.db import migrations, models
import gce_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0006_consultation_approve_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='avatar_utilisateur',
            field=models.FileField(db_column='Avatar', default='avatar/default_avatar.png', upload_to=gce_app.models.avatars_file_path),
        ),
    ]
