# Generated by Django 2.0 on 2018-04-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0006_auto_20180424_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='id_filiere',
            field=models.ForeignKey(blank=True, db_column='id_Filiere', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Filiere'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='id_parcours',
            field=models.ForeignKey(blank=True, db_column='id_Parcours', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Parcours'),
        ),
    ]
