# Generated by Django 2.0 on 2018-04-05 12:27

from django.db import migrations, models
import gce_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0007_auto_20180404_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='avatar_utilisateur',
            field=models.FileField(db_column='Avatar', default='avatars/default_avatar.png', upload_to=gce_app.models.avatars_file_path),
        ),
    ]
