# Generated by Django 2.0 on 2018-04-26 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0007_auto_20180425_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='annee_correction',
            field=models.ForeignKey(blank=True, db_column='annee_Correction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gce_app.AnneeScolaire'),
        ),
    ]
