# Generated by Django 2.0 on 2018-04-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0008_auto_20180405_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versioncopie',
            name='note_copie',
        ),
        migrations.AddField(
            model_name='versioncopie',
            name='note_version',
            field=models.FloatField(blank=True, db_column='note_Version', null=True),
        ),
    ]
