# Generated by Django 2.0 on 2018-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0008_correction_annee_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='copie',
            name='date_affichage',
            field=models.DateField(blank=True, db_column='date_Affichage', null=True),
        ),
    ]
