# Generated by Django 2.0 on 2018-04-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0009_auto_20180406_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='modules',
            field=models.ManyToManyField(blank=True, to='gce_app.Module'),
        ),
    ]
