# Generated by Django 2.0 on 2018-04-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0010_etudiant_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='modules',
        ),
    ]
