# Generated by Django 2.0 on 2018-05-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0013_auto_20180429_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='id_module',
        ),
        migrations.AddField(
            model_name='annonce',
            name='id_module',
            field=models.ManyToManyField(blank=True, to='gce_app.Module'),
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='id_parcours',
        ),
        migrations.AddField(
            model_name='annonce',
            name='id_parcours',
            field=models.ManyToManyField(blank=True, to='gce_app.Parcours'),
        ),
    ]
