# Generated by Django 2.0 on 2018-05-13 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0015_reclamation_approver_reclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='annee_reclamation',
            field=models.ForeignKey(blank=True, db_column='annee_Reclamation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gce_app.AnneeUniv'),
        ),
    ]
