# Generated by Django 2.0 on 2018-05-15 15:39

from django.db import migrations, models
import gce_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0016_reclamation_annee_reclamation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='avatar_utilisateur',
            field=models.FileField(db_column='Avatar', default='default/default_avatar.png', upload_to=gce_app.models.avatars_file_path),
        ),
    ]
