# Generated by Django 2.0 on 2018-05-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0018_reclamation_note_reclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='copie',
            name='rectifier',
            field=models.BooleanField(db_column='Rectifier', default=False),
        ),
    ]
