# Generated by Django 2.0 on 2018-05-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0019_copie_rectifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='approver_reclamation',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='approuver_reclamation',
            field=models.BooleanField(db_column='approuver_Reclamation', default=False),
        ),
    ]
