# Generated by Django 2.0 on 2018-05-16 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0020_auto_20180515_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='copie',
            name='temp_version',
            field=models.ForeignKey(blank=True, db_column='id_tmp', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.VersionCopie'),
        ),
    ]
