# Generated by Django 2.0 on 2018-05-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0021_copie_temp_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copie',
            name='temp_version',
        ),
        migrations.AddField(
            model_name='versioncopie',
            name='temp_version',
            field=models.BooleanField(db_column='Rectifier', default=False),
        ),
    ]
