# Generated by Django 2.0 on 2018-05-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0022_auto_20180516_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='new_files',
            field=models.ManyToManyField(blank=True, related_name='new_files', to='gce_app.FichierCopie'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='old_files',
            field=models.ManyToManyField(blank=True, related_name='old_files', to='gce_app.FichierCopie'),
        ),
    ]
