# Generated by Django 2.0 on 2018-05-17 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0023_auto_20180516_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='note_reclamation',
        ),
    ]
