# Generated by Django 2.0 on 2018-05-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0024_remove_reclamation_note_reclamation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioncopie',
            name='temp_version',
            field=models.BooleanField(db_column='temp_Version', default=False),
        ),
    ]
