# Generated by Django 2.0 on 2018-07-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0028_auto_20180622_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affichage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afficher', models.BooleanField(db_column='afficher_affichage', default=False)),
                ('copies', models.ManyToManyField(blank=True, to='gce_app.Copie')),
                ('id_module', models.ForeignKey(blank=True, db_column='id_Module_affichage', null=True, on_delete=django.db.models.deletion.CASCADE, to='gce_app.Module')),
            ],
            options={
                'db_table': 'Affichage',
            },
        ),
        migrations.RemoveField(
            model_name='discussionadministrative',
            name='id_chef_departement',
        ),
        migrations.RemoveField(
            model_name='discussionadministrative',
            name='id_enseignant',
        ),
        migrations.RemoveField(
            model_name='discussionreclamation',
            name='id_enseignant',
        ),
        migrations.RemoveField(
            model_name='discussionreclamation',
            name='id_reclamation',
        ),
        migrations.RemoveField(
            model_name='messagesadministrative',
            name='id_discussion',
        ),
        migrations.RemoveField(
            model_name='messagesreclamation',
            name='id_discussion',
        ),
        migrations.DeleteModel(
            name='DiscussionAdministrative',
        ),
        migrations.DeleteModel(
            name='DiscussionReclamation',
        ),
        migrations.DeleteModel(
            name='MessagesAdministrative',
        ),
        migrations.DeleteModel(
            name='MessagesReclamation',
        ),
    ]
