# Generated by Django 2.0 on 2018-07-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce_app', '0029_auto_20180725_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affichage',
            name='copies',
            field=models.ManyToManyField(blank=True, to='gce_app.VersionCopie'),
        ),
    ]
